### ISSUE TITLE
Delete systemd journal when preparing the golden image

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/cannolo#14]
1. Install *the* Linux
2. Customize it
3. Delete journal (that's the missing part), as in "delete log messages"
4. Compress the golden image

Points 3 and 4 can be reversed. Low priority, we can leave this task to future generations of developerz.

**Comment by morpheusthewhite** [comment]
Do you think compressing the image is really necessary? It may slow down the process, which I think is what we are trying to avoid

**Comment by lvps** [comment]
@morpheusthewhite Nah, I meant shrinking or anything similar that we're already doing. The important part is point 3, we're already doing the rest and it's good as it is.
