### ISSUE TITLE
Thouroughly test golden image method

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/cannolo#2]
We need to test this method:
- [x] on MBR (BIOS) partition, 32 bit
- [x] on MBR (BIOS) partition, 64 bit 
- [ ] on GPT (UEFI) partition, 32 bit 
- [ ] on GPT (UEFI) partition, 64 bit
and their combinations, on physical machines that we have in lab.

We don't use LVM on our systems, so that's not necessary for now.

**Comment by morpheusthewhite** [comment]
As of now it works on MBR partition (both 32 and 64 bit)

**Comment by e-caste** [comment]
Temporarily closing since we don't need UEFI support at the moment.
