### ISSUE TITLE
Optimize block size for dd

### ISSUE THREAD

**Issue by morpheusthewhite** [WEEE-Open/cannolo#8]
Choosing the appropriate block size for `dd` command may improve the process

Source:
https://stackoverflow.com/questions/6161823/dd-how-to-calculate-optimal-blocksize

**Comment by lvps** [comment]
We could also use `cp /path/to/file.iso /dev/sdx`, which goes at the maximum speed possible and is suggested by the Debian manual somewhere.

The downside is that there is no way to report progress and sometimes it writes the entire file instantly into a cache and terminates, but the kernel still takes many minutes to flush the cache on the actual disk.

The latter problem can be solved by calling `sync` which blocks until all caches are flushed to all disks, but this may not be a good idea if there are other writes in progress to other devices (it blocks until *all* of them terminate). There's apparently no way to sync a single device, only some [patronizing answers](https://unix.stackexchange.com/a/215386) on Stack Exchange telling other people that this does not make sense despite it clearly making sense.

There are [other system calls to do this task](https://stackoverflow.com/a/48172224) but I don't know of any utility that readily invokes them. I can make a small C program that accepts a path to a device and calls `fsync()`, which seems a good candidate, if we want to test that.

**Comment by morpheusthewhite** [comment]
`dd` can still be used. According to [this page](https://www.gnu.org/software/coreutils/manual/html_node/dd-invocation.html#dd-invocation) passing `oflag=sync` will write synchronously to the disk. 

This also reduce the partition. A quick test on an HDD

```
$ sudo dd if=/dev/zero of=/dev/sdb status=progress 
163664384 bytes (164 MB, 156 MiB) copied, 10 s, 16.4 MB/s
320665+0 records in
320665+0 records out
164180480 bytes (164 MB, 157 MiB) copied, 14.0978 s, 11.6 MB/s

sudo dd if=/dev/zero of=/dev/sdb oflag=sync status=progress
29791744 bytes (30 MB, 28 MiB) copied, 13 s, 2.3 MB/s
58313+0 records in
58313+0 records out
29856256 bytes (30 MB, 28 MiB) copied, 13.033 s, 2.3 MB/s
```

Adding the `nocache` flag (which according to the same site requests to discard the system data cache for a file) will not add any overhead

```
sudo dd if=/dev/zero of=/dev/sdb oflag=sync,nocache status=progress
23244800 bytes (23 MB, 22 MiB) copied, 10 s, 2.3 MB/s
46542+0 records in
46542+0 records out
23829504 bytes (24 MB, 23 MiB) copied, 10.2481 s, 2.3 MB/s
```

**Comment by lvps** [comment]
@morpheusthewhite Nice, but we still have to guess the block size asd

**Comment by morpheusthewhite** [comment]
Looking further into the dd flags, `fsync` seems to be the best option for our purpose, since it syncs the disk defore finishing the command, while `sync` syncronize the disk at each block (resulting in a much slower process)

Source: https://unix.stackexchange.com/questions/508701/dd-command-oflag-direct-and-sync-flags 

Testing it on a HDD it does not reduce the performance  
```
$ sudo dd if=/dev/zero of=/dev/sdb bs=4096 count=20000
20000+0 records in
20000+0 records out
81920000 bytes (82 MB, 78 MiB) copied, 2.0414 s, 40.1 MB/s

$ sudo dd if=/dev/zero of=/dev/sdb bs=4096 count=20000 conv=fsync 
20000+0 records in
20000+0 records out
81920000 bytes (82 MB, 78 MiB) copied, 2.04297 s, 40.1 MB/s

$ sudo dd if=/dev/zero of=/dev/sdb bs=4096 count=20000 oflag=sync,nocache
20000+0 records in
20000+0 records out
81920000 bytes (82 MB, 78 MiB) copied, 3.82601 s, 21.4 MB/s
```
